version: '3.8'

services:
  admin:
    build:
      context: .
      dockerfile: admin/Dockerfile
    ports:
      - "3001:5174"
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./admin:/app/admin
      - /app/admin/node_modules

  frontend:
    build:
      context: .
      dockerfile: proyecto-front/Dockerfile
    ports:
      - "8081:5173" # Puerto por defecto de Vite
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./proyecto-front:/app/frontend
      - /app/frontend/node_modules

  backend:
    build:
      context: .
      dockerfile: proyecto-back/Dockerfile
    ports:
      - "5001:5000"
    networks:
      - app-network
    volumes:
      - ./proyecto-back:/app/backend
      - /app/backend/node_modules

networks:
  app-network:
    driver: bridge